In [9]:
import torch
a = torch.randn((2,2,2))
a

tensor([[[-1.2013, -0.2550],
         [-0.8321,  0.3955]],

        [[-0.6937,  0.2817],
         [ 0.6214,  0.2083]]])

In [36]:
import torch
def generate_casual_mask(seq_len):
    casual_mask = torch.ones((seq_len,seq_len)).tril()
    casual_mask = casual_mask.masked_fill(casual_mask == 0, float('-inf'))
    return casual_mask
    

In [38]:
generate_casual_mask(20) == 1

tensor([[ True, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True, False, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  True, False, False, False, False,
         False, False, False, False, False, False, False, False, False, False],
        [ True,  True,  True,  True,  True,  T

In [5]:
import torch
a = torch.randn((4,2,2))
b = torch.randn((4,128))
torch.matmul(a.permute(1,2,0), b) == torch.einsum("SEC, SM -> ECM", a, b)

tensor([[[True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True, True,
          True, True, True, True, T

In [19]:
c=  [
    [[0., 0.3, 0., 0.],
    [0. , 0.,  0., 0.],
    [0.7, 0.,  0., 0.],
    [0.,  0.,  0., 0.]],
     
    [[0., 0, 0., 0.],
    [0. , 0.2,  0., 0.],
    [0., 0.,  0., 0.],
    [0.8,  0.,  0., 0.]],
     
    [[0., 0, 0., 0.],
    [0. , 0.,  0.5, 0.],
    [0., 0.,  0., 0.],
    [0.,  0.5,  0., 0.]],
     
    [[0., 0, 0., 0.],
    [0. , 0.,  0., 0.6],
    [0., 0.,  0., 0.],
    [0.,  0.,  0.4, 0.]],
]
e = torch.tensor(c)
e.shape

torch.Size([4, 4, 4])

In [27]:
c[0]

[[0.0, 0, 0.0, 0.0],
 [0.0, 0.2, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0],
 [0.8, 0.0, 0.0, 0.0]]

In [21]:
e = e.permute(1,2,0)

In [35]:
mask = e.masked_fill(e != 0, 1)

In [37]:
torch.matmul(mask,b)

tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.5972, -1.2585, -0.1010,  ...,  2.4107, -0.9979, -1.0168],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 1.4714, -1.7313,  0.3153,  ...,  1.0781,  0.9243, -1.6988],
         [ 2.0302, -0.6184,  1.3721,  ...,  0.3051, -0.1266, -1.3060],
         [-1.0333,  0.5838,  0.8581,  ...,  0.7061, -1.1515,  0.0612]],

        [[ 0.5972, -1.2585, -0.1010,  ...,  2.4107, -0.9979, -1.0168],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],

        [[ 1.4714, -1.7313,  0.3153,  ...,  1.0781,  0.9243, -1.6988],
         [ 2.0302, -0.6184,  1.3721,  ...,  0.3051, -0.1266, -1.3060],


In [1]:
a= [1,2,3,4]
a[3:]

[4]