In [8]:
import torch
a = torch.randn((32,128,10,512))
q_absorb = torch.randn(64,128,512)  
torch.einsum('chd, bhsd -> bhsc', q_absorb.squeeze(), a)

tensor([[[[ 2.2809e+01,  1.4952e+01, -1.1303e+00,  ...,  1.8455e+01,
           -2.1506e+01, -4.1262e+01],
          [-1.4627e+01,  6.4021e+00,  2.8029e+01,  ..., -5.1422e+01,
           -2.4069e+01,  4.0236e+01],
          [-2.4837e+01, -1.2850e+01, -1.9254e+00,  ..., -4.1150e+00,
            2.5032e+01,  1.5486e+01],
          ...,
          [ 1.7066e+01, -6.1663e+00,  4.3327e+00,  ..., -1.7453e+01,
           -2.6569e+01,  1.3433e+01],
          [-3.5394e+01, -1.2195e+01, -4.5078e+00,  ...,  6.6970e+00,
           -2.4699e+01, -4.7164e+00],
          [ 4.2799e+01, -4.4825e+00, -5.8599e+01,  ...,  2.1944e+01,
           -2.4597e+01,  2.6281e+01]],

         [[-1.2476e+01, -8.3371e+00, -9.5810e+00,  ...,  1.3518e+01,
           -2.7814e+01,  6.1847e-01],
          [ 4.5141e+01, -3.2094e+01, -2.6427e+01,  ...,  2.9087e+01,
            3.6434e+01,  1.3997e+01],
          [ 3.0843e+00, -2.7817e+00, -4.2471e+00,  ...,  3.4981e+01,
           -3.0710e+01, -1.2040e+01],
          ...,
     

In [7]:
torch.randn(2,3,4).t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 3D

In [39]:
import torch
# e, topk, bs*seq
a = torch.nn.functional.one_hot(torch.tensor([[0,1],[1,2],[1,2]]), num_classes=3).permute(2,1,0)
a

tensor([[[1, 0, 0],
         [0, 0, 0]],

        [[0, 1, 1],
         [1, 0, 0]],

        [[0, 0, 0],
         [0, 1, 1]]])

In [40]:
torch.where(condition=a[1])

(tensor([0, 0, 1]), tensor([1, 2, 0]))

In [2]:
a = [1,2,3]
a[0:3]

[1, 2, 3]

In [3]:
a = "abc"
a.

['abc']